image: cirrusci/flutter:stable

before_script:
  - flutter pub get

stages:
  - analyze-and-test

analyze:
  stage: analyze-and-test
  script:
    - flutter analyze

test:
  stage: analyze-and-test
  script:
    - flutter test
