image: cirrusci/flutter:2.10.5

before_script:
  - flutter pub get

stages:
  - analyze-and-test

lint:
  stage: analyze-and-test
  script:
    - flutter analyze

test:
  stage: analyze-and-test
  script:
    - make test
