image: cirrusci/flutter:stable

before_script:
  - flutter pub get

stages:
  - analyze-and-test

check-license:
  stage: analyze-and-test
  script:
    - bash ./.githooks/license_validation.sh ./lib/ .dart
    - bash ./.githooks/license_validation.sh ./test/ .dart

lint:
  stage: analyze-and-test
  script:
    - flutter analyze

test:
  stage: analyze-and-test
  script:
    - make test
