name: git_ihm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  git: ^2.0.0
  provider: ^6.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6595
  expandable: ^5.0.1
  path_provider: ^2.0.8
  path: ^1.8.0
  flutter_treeview: ^1.0.7+1
  intl: ^0.18.0
  timeago: ^3.2.2
  easy_sidemenu: ^0.4.1+1
  flutter_gravatar: ^2.0.2  
  desktop_window: ^0.4.0
  google_fonts: ^4.0.3
  file_picker: ^5.2.11
  file_selector: ^0.9.5
  logger: ^2.0.1
  package_info_plus: ^4.0.2
  connectivity_plus: ^4.0.1
  flutter_local_notifications: ^15.1.1
  url_launcher: ^6.1.14
  fluttertoast: ^8.2.3

dev_dependencies:
  mockito: ^5.2.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.17.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: FantasqueSansMono
      fonts:
        - asset: assets/fonts/FantasqueSansMono-Regular.ttf
        - asset: assets/fonts/FantasqueSansMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/FantasqueSansMono-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/FantasqueSansMono-Italic.ttf
          style: italic

    - family: Hack
      fonts:
        - asset: assets/fonts/Hack-Regular.ttf
        - asset: assets/fonts/Hack-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hack-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Hack-Italic.ttf
          style: italic
    - family: Seti
      fonts:
        - asset: assets/fonts/seti.ttf

